esphome:
  name: esp32c6-deepsleep
  friendly_name: ESP32-C6 DeepSleep

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome
    password: "e874cdd94f9bba5fd453fce40061e811"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ESP32C6-Fallback"
    password: "12345678"

captive_portal:

web_server:
  port: 80

deep_sleep:
  id: ds_5min
  sleep_duration: 5min

button:
  - platform: template
    name: "Deep Sleep 5 Minuten"
    icon: "mdi:sleep"
    on_press:
      - logger.log: "Gehe jetzt für 5 Minuten in Deep Sleep..."
      - delay: 500ms
      - deep_sleep.enter: ds_5min

output:
  - platform: gpio
    pin: GPIO8
    id: led_green

light:
  - platform: binary
    output: led_green
    id: status_led
    internal: true
    restore_mode: ALWAYS_OFF