esphome:
  name: book-nook-alley
  friendly_name: Book-Nook-Alley

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "yLQibxsOAtbJJBctz1/E33lVPLUb1VUb+e4KEsMN620="

ota:
  password: "e874cdd94f9bba5fd453fce40061e810"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Book-Nook-Alley Fallback Hotspot"
    password: "kdYn9Sd0PO1s"

captive_portal:
web_server:

# ====== EINSTELLUNG: Aktiv-Logik ======
# Viele Board-LEDs sind "active low" (inverted).
# Lass zuerst 'inverted: false'. Wenn eine LED immer "aus" bleibt, probier 'inverted: true' NUR für diesen Pin.
# (Du kannst es auch pauschal true setzen, wenn deine LEDs gegen 3V3 liegen.)
# ======================================

# ---------- Ausgänge (ESP32 „sichere“ GPIOs, alle als Output nutzbar) ----------
# Meide 0 (Boot), 6–11 (Flash), 34–39 (nur Input). 12 kann Boot beeinflussen – hier weggelassen.
output:
  - platform: gpio
    id: out_gpio2
    pin: GPIO2
    inverted: false
  - platform: gpio
    id: out_gpio4
    pin: GPIO4
    inverted: false
  - platform: gpio
    id: out_gpio5
    pin: GPIO5
    inverted: false
  - platform: gpio
    id: out_gpio13
    pin: GPIO13
    inverted: false
  - platform: gpio
    id: out_gpio14
    pin: GPIO14
    inverted: false
  - platform: gpio
    id: out_gpio15
    pin: GPIO15
    inverted: false
  - platform: gpio
    id: out_gpio18
    pin: GPIO18
    inverted: false
  - platform: gpio
    id: out_gpio19
    pin: GPIO19
    inverted: false
  - platform: gpio
    id: out_gpio21
    pin: GPIO21
    inverted: false
  - platform: gpio
    id: out_gpio22
    pin: GPIO22
    inverted: false
  - platform: gpio
    id: out_gpio23
    pin: GPIO23
    inverted: false
  - platform: gpio
    id: out_gpio25
    pin: GPIO25
    inverted: false
  - platform: gpio
    id: out_gpio26
    pin: GPIO26
    inverted: false
  - platform: gpio
    id: out_gpio27
    pin: GPIO27
    inverted: false
  - platform: gpio
    id: out_gpio32
    pin: GPIO32
    inverted: false
  - platform: gpio
    id: out_gpio33
    pin: GPIO33
    inverted: false

# ---------- Manuelle Test-Schalter im Web-UI / Home Assistant ----------
switch:
  - platform: output
    name: "GPIO2"
    id: sw_gpio2
    output: out_gpio2
  - platform: output
    name: "GPIO4"
    id: sw_gpio4
    output: out_gpio4
  - platform: output
    name: "GPIO5"
    id: sw_gpio5
    output: out_gpio5
  - platform: output
    name: "GPIO13"
    id: sw_gpio13
    output: out_gpio13
  - platform: output
    name: "GPIO14"
    id: sw_gpio14
    output: out_gpio14
  - platform: output
    name: "GPIO15"
    id: sw_gpio15
    output: out_gpio15
  - platform: output
    name: "GPIO18"
    id: sw_gpio18
    output: out_gpio18
  - platform: output
    name: "GPIO19"
    id: sw_gpio19
    output: out_gpio19
  - platform: output
    name: "GPIO21"
    id: sw_gpio21
    output: out_gpio21
  - platform: output
    name: "GPIO22"
    id: sw_gpio22
    output: out_gpio22
  - platform: output
    name: "GPIO23"
    id: sw_gpio23
    output: out_gpio23
  - platform: output
    name: "GPIO25"
    id: sw_gpio25
    output: out_gpio25
  - platform: output
    name: "GPIO26"
    id: sw_gpio26
    output: out_gpio26
  - platform: output
    name: "GPIO27"
    id: sw_gpio27
    output: out_gpio27
  - platform: output
    name: "GPIO32"
    id: sw_gpio32
    output: out_gpio32
  - platform: output
    name: "GPIO33"
    id: sw_gpio33
    output: out_gpio33

# ---------- Start-/Stop-Buttons für den automatischen Zyklus ----------
button:
  - platform: template
    name: "LED-Zyklus START"
    on_press:
      - script.execute: cycle_test
  - platform: template
    name: "LED-Zyklus STOP"
    on_press:
      - script.stop: cycle_test
      - script.execute: all_off

# ---------- Test-Skripte ----------
script:
  - id: all_off
    mode: restart
    then:
      - output.turn_off: out_gpio2
      - output.turn_off: out_gpio4
      - output.turn_off: out_gpio5
      - output.turn_off: out_gpio13
      - output.turn_off: out_gpio14
      - output.turn_off: out_gpio15
      - output.turn_off: out_gpio18
      - output.turn_off: out_gpio19
      - output.turn_off: out_gpio21
      - output.turn_off: out_gpio22
      - output.turn_off: out_gpio23
      - output.turn_off: out_gpio25
      - output.turn_off: out_gpio26
      - output.turn_off: out_gpio27
      - output.turn_off: out_gpio32
      - output.turn_off: out_gpio33

  - id: cycle_test
    mode: restart
    then:
      - script.execute: all_off
      - while:
          condition:
            lambda: |-
              return true;   // Endlosschleife
          then:
            # Pro Schritt genau EIN Pin an (1s), dann aus (0.2s), weiter
            - output.turn_on: out_gpio2
            - delay: 1s
            - output.turn_off: out_gpio2
            - delay: 200ms

            - output.turn_on: out_gpio4
            - delay: 1s
            - output.turn_off: out_gpio4
            - delay: 200ms

            - output.turn_on: out_gpio5
            - delay: 1s
            - output.turn_off: out_gpio5
            - delay: 200ms

            - output.turn_on: out_gpio13
            - delay: 1s
            - output.turn_off: out_gpio13
            - delay: 200ms

            - output.turn_on: out_gpio14
            - delay: 1s
            - output.turn_off: out_gpio14
            - delay: 200ms

            - output.turn_on: out_gpio15
            - delay: 1s
            - output.turn_off: out_gpio15
            - delay: 200ms

            - output.turn_on: out_gpio18
            - delay: 1s
            - output.turn_off: out_gpio18
            - delay: 200ms

            - output.turn_on: out_gpio19
            - delay: 1s
            - output.turn_off: out_gpio19
            - delay: 200ms

            - output.turn_on: out_gpio21
            - delay: 1s
            - output.turn_off: out_gpio21
            - delay: 200ms

            - output.turn_on: out_gpio22
            - delay: 1s
            - output.turn_off: out_gpio22
            - delay: 200ms

            - output.turn_on: out_gpio23
            - delay: 1s
            - output.turn_off: out_gpio23
            - delay: 200ms

            - output.turn_on: out_gpio25
            - delay: 1s
            - output.turn_off: out_gpio25
            - delay: 200ms

            - output.turn_on: out_gpio26
            - delay: 1s
            - output.turn_off: out_gpio26
            - delay: 200ms

            - output.turn_on: out_gpio27
            - delay: 1s
            - output.turn_off: out_gpio27
            - delay: 200ms

            - output.turn_on: out_gpio32
            - delay: 1s
            - output.turn_off: out_gpio32
            - delay: 200ms

            - output.turn_on: out_gpio33
            - delay: 1s
            - output.turn_off: out_gpio33
            - delay: 200ms
    