esphome:
  name: pflanzenfreund
  friendly_name: PflanzenFreund

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "zrum3G3WGZ0DPgQ7KrZxW5BGcXXLt7VJMJtCXybyE+Y="

ota:
  password: "00294cf265378bc20ab75534e579dc1b"

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pflanzenfreund Fallback Hotspot"
    password: "sojtD5PzbOae"

captive_portal:

globals:
  - id: pour
    type: int
    restore_value: no
    initial_value: '0' 


time:
- platform: sntp
  servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
  on_time:
    - seconds: 30
      then:
      - logger.log:
          format: "off %.5f"
          args: [ 'id(soil_moisture_id).state' ]
      - lambda: |-
          if(id(soil_moisture_id).state < 70 || id(pour) == 1){
             ESP_LOGD("main", "dry");
             id(pump_relay_id).turn_on();
             id(pour) = 1;
          }
          
          if(id(soil_moisture_id).state > 90){
             ESP_LOGD("main", "wet");
             id(pump_relay_id).turn_off();
             id(pour) = 0;
          } 
    - seconds: 37
      then:
       - logger.log:
           format: "pause %.5f"
           args: [ 'id(soil_moisture_id).state' ]
       - lambda: id(pump_relay_id).turn_off();
        
sensor:
- platform: adc
  pin: A0
  name: "Soil Moisture"
  id: "soil_moisture_id"
  update_interval: 1s
  unit_of_measurement: "%"
  filters:
  - median:
      window_size: 7
      send_every: 4
      send_first_at: 1
  - calibrate_linear:
      - 0.73 -> 0.00
      - 0.328 -> 100.00
  - lambda: if (x < 1) return 0; else return (x);
  on_value: 
     then:
      - logger.log:
         format: "The sensor reports value %.5f"
         args: [ 'id(soil_moisture_id).raw_state' ]
  accuracy_decimals: 0

switch:
  platform: gpio
  name: "Pump Relay"
  id:   "pump_relay_id"
  pin: GPIO16
  on_turn_on:
    then:
    - logger.log:
        format: "on %.5f"
        args: [ 'id(soil_moisture_id).raw_state' ]
  on_turn_off:
    then:
    - logger.log:
        format: "off %.5f"
        args: [ 'id(soil_moisture_id).raw_state' ]


    