esphome:
  name: scale
  platform: ESP8266
  board: nodemcu
  
globals:
  - id: tara_value
    type: float
    restore_value: no
    initial_value: '0.0' 
  - id: weight_value
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: sensor_timer
    type: float
    restore_value: no
    initial_value: '0' 



# Enable logging
logger:
  level: WARN


# Enable Home Assistant API
api:

ota:
  password: "00f55bf6fc92f5d709f5756a38046d5f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
      # Set this to the IP of the ESP
      static_ip: 192.168.178.129
      # Set this to the IP address of the router. Often ends with .1
      gateway: 192.168.178.1
      # The subnet of the network. 255.255.255.0 works for most home networks.
      subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tim Fallback Hotspot"
    password: "aH7nlctFFXx5"
    
http_request:
  useragent: esphome/device
  timeout: 10s
    
web_server:
  port: 80
    
    
sensor:
  - platform: hx711
    name: "HX711 Value"
    id: "scale_id"
    dout_pin: D2
    clk_pin: D3
    gain: 128
    update_interval: 100ms
    unit_of_measurement: g
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
          - 111140 -> 0
          - 212335 -> 216
      - lambda:  |-
          return x - id(tara_value) ;
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
    on_value: 
      then:
       - lambda: |-
          id(weight_value) = x;
       - http_request.post:
             url: !lambda |-
              if(x < 12 && id(start_grind).state){
                    return "http://192.168.178.125/switch/relay/turn_on";
                  } else if(x < 15 && id(start_grind).state){
                    if(id(sensor_timer) <= 16){
                      id(sensor_timer)+=1;
                      return "http://192.168.178.125/switch/relay/turn_off"; 
                    }else if(id(sensor_timer) > 15){
                      id(sensor_timer)+=1;
                      if(id(sensor_timer) > 19){
                        id(sensor_timer) = 0;
                      }
                      return "http://192.168.178.125/switch/relay/turn_on";
                    }
                  } 
                  return "http://192.168.178.125/switch/relay/turn_off";
                  
binary_sensor:
  - platform: gpio
    pin: 
     number: 2
     mode:
        input: true
        pullup: true
    name: "start_grind"
    id: "start_grind"
    filters:
      - invert:
    on_press:
      then:
      - lambda: |-
          id(tara_value) += id(weight_value);
          id(sensor_timer) = 0;
          
captive_portal:
    