esphome:
  name: smurf-house

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "44e46DGkTdCKUZWQ+nlUpoCzApq5FFJW1fPHK5QEhKw="
    
  services:
    - service: color_picker
      variables:
        red: float
        green: float
        blue: float
      then:
        - light.turn_on:
            id: smurf_light
            red: !lambda 'return red;'
            green: !lambda 'return green;'
            blue: !lambda 'return blue;'

ota:
  password: "1988c6d0a635f207adcd1cbe561ab9c1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
      # Set this to the IP of the ESP
      static_ip: 192.168.178.121
      # Set this to the IP address of the router. Often ends with .1
      gateway: 192.168.178.1
      # The subnet of the network. 255.255.255.0 works for most home networks.
      subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smurf-House Fallback Hotspot"
    password: "Zi7Se2bScwKC"
    
web_server:
  port: 80
  
light:
  - platform: rgb
    name: "smurf_light"
    id: "smurf_light"
    red: output_red
    green: output_green
    blue: output_blue
    on_turn_on:
      then:
      - light.turn_on:
          id: smurf_light
          brightness: 100%
          red: 100%
          green: 0%
          blue: 0%
    effects:
      - random:
          name: Random Effect With Custom Values
          transition_length: 5s
          update_interval: 7s

# Example output entry
output:
  - platform: ledc
    id: output_red
    pin: GPIO4
  - platform: ledc
    id: output_green
    pin: GPIO17
  - platform: ledc
    id: output_blue
    pin: GPIO16



captive_portal:
    