esphome:
  name: solarpflanzenfreund
  friendly_name: SolarPflanzenFreund

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3Z4+NJR8gUzOK67zFYo7/BpZreSZv6+Aq5Ys773tFnc="

ota:
  password: "8855ed4d064ac6f1e1cf312af3dc53aa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Solarpflanzenfreund"
    password: "4S7OvDFwbJXg"

captive_portal:

web_server:
  port: 80

deep_sleep:
  run_duration: 120s
  sleep_duration: 30s


time:
- platform: sntp
  servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
  on_time:
    - seconds: /10
      then:
      - logger.log: "wake"
    