substitutions:
  devicename: switchbot-steamdeck
  sb_mac: "F2:B2:04:86:0E:3D"

esphome:
  name: ${devicename}

esp32:
  variant: esp32c6
  framework:
    type: esp-idf

logger:
  baud_rate: 115200

# Enable Home Assistant API
api:
  encryption:
    key: "yLQibxsOAtbJJBctz1/E33lVPLUb1VUb+e4KEsMN622="

ota:
  - platform: esphome
    password: "e874cdd94f9bba5fd453fce40061e813"

web_server: 
 port: 80 
captive_portal:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    active: true

ble_client:
  - id: sb_bot
    mac_address: ${sb_mac}

script:
  - id: sb_press
    mode: queued
    then:
      - ble_client.connect: sb_bot
      - delay: 800ms
      - ble_client.ble_write:
          id: sb_bot
          service_uuid: "cba20d00-224d-11e6-9fb8-0002a5d5c51b"
          characteristic_uuid: "cba20002-224d-11e6-9fb8-0002a5d5c51b"
          value: !lambda |-
            // SwitchBot Bot "press": 57 01 00 (unencrypted)
            return std::vector<uint8_t>({0x57, 0x01, 0x00});
      - delay: 200ms
      - ble_client.disconnect: sb_bot


button:
  - platform: template
    name: "SwitchBot Press"
    on_press:
      - script.execute: sb_press
  - platform: remote_receiver
    name: "SteamDeck Pronto Button"
    pronto:
      data: >-
        0000 006D 0010 0000 000E 001A 000D 0044 000D 001B 000D 001B 000D 001B
        000D 001B 000D 001B 000D 001B 000D 001B 000D 0044 000D 001B 000D 001B
        000D 0044 000D 001B 000D 001B 000D 0180
      # delta: 200   # optional tolerance if it doesn't match reliably
    filters:
      - delayed_off: 300ms
    on_press:
      then:
        - script.execute: sb_press
        - logger.log: "Matched the Pronto command!"


remote_receiver:
  pin: GPIO02
  dump: pronto   # or all while testing

