esphome:
  name: switchbot--steamdeck
  friendly_name: switchbot - steamdeck

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "P4jaOpTlEZGWkizh5JHW8idPkK5pKm99dRe4F3up058="

ota:
  - platform: esphome
    password: "3797a045f7ee1555f67ef4f9db13ee31"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Switchbot--Steamdeck"
    password: "bl42Z8d5BXjm"

captive_portal:

web_server:
  port: 80

esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 1100ms
    window: 110ms

  on_ble_advertise:
    then:
      - lambda: |-
          // Logge alles, was nach SwitchBot aussieht (oder logge erstmal alles)
          if (x.get_name().size()) {
            ESP_LOGD("ble_adv", "ADV name=%s addr=%s rssi=%d",
                     x.get_name().c_str(), x.address_str().c_str(), x.get_rssi());
          }
# "F2:B2:04:86:0E:3D"
ble_client:
  - mac_address: "C0:33:12:35:BC:CE"
    id: bot
    auto_connect: false

    on_connect:
      then:
        - logger.log: "BLE CONNECTED"
        - ble_client.ble_write:
            id: bot
            service_uuid: "cba20d00-224d-11e6-9fb8-0002a5d5c51b"
            characteristic_uuid: "cba20002-224d-11e6-9fb8-0002a5d5c51b"
            value: [0x57, 0x01, 0x00]
        - logger.log: "BLE WRITE SENT"
        - delay: 300ms
        - ble_client.disconnect: bot
        - logger.log: "BLE DISCONNECTED"
        - lambda: 'id(busy) = false;'
        - switch.turn_off: hw_switch

    on_disconnect:
      then:
        - logger.log: "BLE DISCONNECTED EVENT"
        - lambda: 'id(busy) = false;'

globals:
  - id: busy
    type: bool
    initial_value: "false"

switch:
  - platform: template
    name: "Hardware Button"
    id: hw_switch

    turn_on_action:
      - logger.log: "SWITCH PRESSED"
      - if:
          condition:
            lambda: 'return !id(busy);'
          then:
            - logger.log: "START CONNECT"
            - lambda: 'id(busy) = true;'
            - ble_client.connect: bot
          else:
            - logger.log: "IGNORED - BUSY"